
CREATE OR REPLACE PROCEDURE GETALLEMPLOYEES
DYNAMIC RESULT SETS 1
P1: BEGIN 
	DECLARE C1 CURSOR WITH RETURN
	FOR SELECT EMPNO, LASTNAME, FIRSTNME, SEX, WORKDEPT, JOB, SALARY 
	FROM EMPLOYEE
	ORDER BY LASTNAME;
OPEN C1;
END P1